config/routes.rb
Rails.application.routes.draw do
  get 'user_index' => 'backroom#user_index'
  put 'upgrade_user' => 'backroom#upgrade_user'
  put 'downgrade_user' => 'backroom#downgrade_user'

  get 'delete_from_cart' => 'cart#delete_from_cart'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  post 'order_complete' => 'cart#order_complete'
  put 'update_quant' => 'cart#update_quant'

  devise_for :users

  get root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order, :delete_from_cart]

  def add_to_cart
    @order = current_order
    line_item = @order.line_items.find_by(product_id: params[:product_id])
    if line_item.blank?
      line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
      @order.save
      session[:order_id] = @order.id
    else
      line_item.update(quantity: line_item.quantity += params[:quantity].to_i)
    end

    line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
    redirect_back(fallback_location: root_path)
  end

  def view_order
    @line_items = current_order.line_items
  end

  def checkout
    line_items = current_order.line_items
    unless line_items.length == 0
      current_order.update(user_id: current_user.id, subtotal: 0)
      @order = current_order

      line_items.each do |line_item|
        line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
        @order.order_items[line_item.product_id] = line_item.quantity
        @order.subtotal += line_item.line_item_total
      end
      @order.save
      @order.update(sales_tax: (@order.subtotal * 0.07))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))
      session[:order_id] = nil
    end
  end

  def delete_from_cart
    line_item = LineItem.find(params[:id])
    line_item.destroy
    redirect_back(fallback_location: root_path)
  end

  def update_quant
    line_item = LineItem.find(params[:id])
    line_item.update(quantity: params[:quantity])
    line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
    redirect_back(fallback_location: root_path)
  end


  def order_complete
    @order = Order.find(params[:order_id])
    @order.line_items.destroy_all
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i
    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
      )
    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe Customer',
      :currency => 'usd'
      )
    rescue Stripe::CardError => e
    flash[:error] = e.message
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thanks for Shopping with Us!</h2>
<p>Let's review your order:</p>

<% @order.order_items.each do |k, v| %>
  <ul>
    <li><%= Product.find(k).name %>: <%= v %></li>
  </ul>
<% end %>

<p><strong>Order Total: </strong> <%= number_to_currency @order.grand_total %></p>

<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <%= hidden_field_tag :order_id, @order.id %>

    <script type="text/javascript" src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Order #<%= @order.id %>" data-amount="<%= (@order.grand_total.to_f.round(2) * 100).to_i %>"></script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>Order #<%= @order.id %> will be shipping to you, <%= @order.user.email %>, as soon as possible!</p>

app/views/cart/view_order.html.erb
<h1 class="text-center">My Cart</h1>

<div>
  <% @line_items.each do |line_item| %>
    <div class="media">
      <div class="media-left">
        <% if line_item.product.image.blank? == false %>
          <%= image_tag line_item.product.image.url, size: 64 %>
        <% end %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= line_item.product.name %>: <small><%= number_to_currency line_item.product.price %></small></h4>
        <p>Quantity: <%= line_item.quantity %> (<%= line_item.product.quantity %> in stock)
          <%= form_tag(update_quant_path, method: :put) do %>
            <%= number_field_tag :quantity, line_item.quantity, min: 1, max: line_item.product.quantity %>
            <%= hidden_field_tag :id, line_item.id %>
            <%= submit_tag 'Update', class: 'btn btn-default' %>
          <% end %>
        </p>
        <p>Subtotal: <%= number_to_currency line_item.line_item_total %></p>
      </div>
      <div class="media-right">
        <%= link_to 'Remove from Cart', delete_from_cart_path(id: line_item.id), class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

<div class="text-center">
  <%= link_to 'Proceed to Checkout?', checkout_path, class: "btn btn-success" %>
</div>