config/routes.rb
Rails.application.routes.draw do
  get 'user_index' => 'backroom#user_index'
  put 'upgrade_user' => 'backroom#upgrade_user'
  put 'downgrade_user' => 'backroom#downgrade_user'

  get 'delete_from_cart' => 'cart#delete_from_cart'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  post 'order_complete' => 'cart#order_complete'
  put 'update_quant' => 'cart#update_quant'

  devise_for :users

  get root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backroom_controller.rb
class BackroomController < ApplicationController
  before_action :authenticate_user!

  def user_index
    @users = User.all
    authorize! :read, User
  end

  def upgrade_user
    user = User.find(params[:id])
    user.update(role: 'admin')
    redirect_to user_index_path
  end

  def downgrade_user
    user = User.find(params[:id])
    user.update(role: 'guest')
    redirect_to user_index_path
  end
end

app/helpers/backroom_helper.rb
module BackroomHelper
end

app/views/backroom/user_index.html.erb
<h1>All Users</h1>

<table class="table">
  <tr>
    <th>User Email</th>
    <th>User Role</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.role %></td>
      <td>
        <% if user.role == 'guest' %>
          <%= link_to 'Upgrade to Admin', upgrade_user_path(id: user.id), method: :put, class: 'btn btn-success' %>
        <% elsif user.role == 'admin' && user.id != current_user.id %>
          <%= link_to 'Make Guest', downgrade_user_path(id: user.id), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>